/**
 * Catalog report.
 *
 * Reads src/data/generated/catalog.json and writes docs/CATALOG-REPORT.md: a
 * full census of the catalog as it currently stands, plus everything a person
 * needs to act on. Re-run it after any import.
 *
 * Usage: node scripts/catalog-report.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(import.meta.url), "..", "..");

interface Variant {
  id: string;
  title: string;
  sku: string | null;
  priceCents: number;
  compareAtCents: number | null;
  weightGrams: number | null;
}

interface Product {
  handle: string;
  title: string;
  brandId: string;
  categoryId: string | null;
  collections: string[];
  productType: string | null;
  shortBenefit: string | null;
  description: string[];
  quarantinedContent: { text: string; matches: { reason: string; term: string }[] }[];
  images: { src: string; alt: string }[];
  pendingImages: { path: string; sourceUrl: string }[];
  variants: Variant[];
  seo: { title: string | null; description: string | null };
  subscription: boolean;
  priceProvisional: boolean;
  publishable: boolean;
  titleMatches: { reason: string; term: string }[];
  status: string;
  flags: string[];
  sources: { file: string; row: number; handle: string; sku: string | null }[];
}

interface Duplicate {
  keptHandle: string;
  duplicateOf: string;
  matchedOn: string;
  file: string;
  row: number;
  filled: string[];
  conflicts: { field: string; kept: string; ignored: string }[];
}

const cat = JSON.parse(
  readFileSync(join(root, "src", "data", "generated", "catalog.json"), "utf8"),
) as {
  meta: { sources: string[]; sourceRows: number; duplicatesMerged: number; skipped: number };
  products: Product[];
  duplicates: Duplicate[];
  skipped: { handle: string; reason: string; file?: string }[];
};

const P = cat.products;
const money = (c: number) => `$${(c / 100).toFixed(2)}`;
const count = <T>(xs: T[], f: (x: T) => string | null) => {
  const m = new Map<string, number>();
  for (const x of xs) {
    const k = f(x);
    if (k !== null) m.set(k, (m.get(k) ?? 0) + 1);
  }
  return [...m].sort((a, b) => b[1] - a[1]);
};

const BRAND_NAME: Record<string, string> = {
  solutionshocl: "SolutionsHOCL",
  "life-ionizers": "Life Ionizers",
  "pitcher-of-life": "Pitcher of Life",
  "hawaiian-volcanic-organic": "Hawaiian Volcanic Organic",
  "life-sciences-water": "Life Sciences Water",
};

const FLAG_LABEL: Record<string, string> = {
  inventory_unknown: "No stock quantity in the source",
  missing_seo_title: "No SEO title",
  missing_image_alt: "No image alt text",
  missing_source_category: "No category in the source",
  content_quarantined: "Some copy held for compliance review",
  missing_seo_description: "No SEO description",
  missing_sku: "No SKU",
  missing_type: "No product type",
  missing_weight: "No shipping weight",
  missing_short_benefit: "No card benefit line",
  missing_description: "No description at all",
  zero_price: "Price is 0.00",
  missing_price: "No price",
  title_not_publishable: "Product name states a banned claim",
  all_content_quarantined: "All copy held for compliance review",
  missing_image: "No image",
  image_asset_pending: "Image file not present locally",
  no_collection_mapping: "No collection mapping",
  source_conflict: "Sources disagree on a value",
};

const variants = P.flatMap((p) => p.variants);
const images = P.flatMap((p) => p.images);
const published = P.filter((p) => p.publishable);
const withheld = P.filter((p) => !p.publishable);
const review = P.filter((p) => p.status === "needs_review");
const flagCounts = count(
  P.flatMap((p) => p.flags.map((f) => ({ f }))),
  (x) => x.f,
);

const L: string[] = [];
const w = (s = "") => L.push(s);

w("# Catalog report");
w();
w(`Generated by \`scripts/catalog-report.ts\` from \`src/data/generated/catalog.json\`.`);
w();
w(`Sources: ${cat.meta.sources.map((s) => `\`${s}\``).join(", ")}`);
w();

/* ------------------------------- totals -------------------------------- */

w("## Totals");
w();
w("| | Count |");
w("|---|---:|");
w(`| Source rows read | ${cat.meta.sourceRows} |`);
w(`| Duplicate rows merged | ${cat.meta.duplicatesMerged} |`);
w(`| Rows skipped | ${cat.meta.skipped} |`);
w(`| **Unique products** | **${P.length}** |`);
w(`| Published to the storefront | ${published.length} |`);
w(`| Withheld pending a decision | ${withheld.length} |`);
w(`| Requiring manual review | ${review.length} |`);
w(`| Variants | ${variants.length} |`);
w(`| Distinct SKUs | ${new Set(variants.map((v) => v.sku).filter(Boolean)).size} |`);
w(`| Images linked | ${images.length} |`);
w(`| Distinct image files | ${new Set(images.map((i) => i.src)).size} |`);
w(`| Brands | ${new Set(P.map((p) => p.brandId)).size} |`);
w(`| Collections | ${new Set(P.flatMap((p) => p.collections)).size} |`);
w(`| Categories | ${new Set(P.map((p) => p.categoryId).filter(Boolean)).size} |`);
w();

/* ------------------------------- brands -------------------------------- */

w("## Brands");
w();
w("| Brand | Products | Variants | With image | Published |");
w("|---|---:|---:|---:|---:|");
for (const [b, n] of count(P, (p) => p.brandId)) {
  const of = P.filter((p) => p.brandId === b);
  w(
    `| ${BRAND_NAME[b] ?? b} | ${n} | ${of.flatMap((p) => p.variants).length} | ` +
      `${of.filter((p) => p.images.length).length} | ${of.filter((p) => p.publishable).length} |`,
  );
}
w();

/* ---------------------------- collections ------------------------------ */

w("## Collections");
w();
w("| Collection | Products |");
w("|---|---:|");
for (const [c, n] of count(
  P.flatMap((p) => p.collections.map((c) => ({ c }))),
  (x) => x.c,
)) {
  w(`| \`${c}\` | ${n} |`);
}
w();
w("## Categories");
w();
w("| Category | Products |");
w("|---|---:|");
for (const [c, n] of count(P, (p) => p.categoryId)) w(`| ${c} | ${n} |`);
w();

/* ------------------------------ variants ------------------------------- */

const prices = variants.map((v) => v.priceCents).sort((a, b) => a - b);
const median = prices[Math.floor(prices.length / 2)] ?? 0;
w("## Variants and pricing");
w();
w("| | |");
w("|---|---|");
w(`| Variants | ${variants.length} |`);
w(`| Products with more than one variant | ${P.filter((p) => p.variants.length > 1).length} |`);
w(`| Price range | ${money(prices[0] ?? 0)} to ${money(prices[prices.length - 1] ?? 0)} |`);
w(`| Median price | ${money(median)} |`);
w(`| Priced at 0.00 | ${variants.filter((v) => v.priceCents === 0).length} |`);
w(`| With a compare-at price | ${variants.filter((v) => v.compareAtCents !== null).length} |`);
w(`| With a SKU | ${variants.filter((v) => v.sku).length} of ${variants.length} |`);
w(`| With a shipping weight | ${variants.filter((v) => v.weightGrams !== null).length} of ${variants.length} |`);
w();
w("Money is stored as integer cents throughout. Stock quantities are not present");
w("in any source, so availability is unresolved for every product.");
w();

/* ------------------------------- images -------------------------------- */

w("## Images");
w();
w("| | Count |");
w("|---|---:|");
w(`| Products with at least one image | ${P.filter((p) => p.images.length).length} |`);
w(`| Products with no image | ${P.filter((p) => !p.images.length).length} |`);
w(`| Image references linked | ${images.length} |`);
w(`| Awaiting an asset upload | ${P.reduce((n, p) => n + p.pendingImages.length, 0)} |`);
w(`| Missing alt text | ${P.filter((p) => p.flags.includes("missing_image_alt")).length} |`);
w();
w("Every image resolves to an EarthTrade-served path. No third-party host appears");
w("in the catalog.");
w();

/* ----------------------------- duplicates ------------------------------ */

w("## Duplicates");
w();
if (!cat.duplicates.length) {
  w("No duplicate rows were found. Every source row produced a distinct product.");
  w();
  w("Deduplication matches on handle first, then on SKU, so the same product");
  w("arriving from another export under a different slug is still recognised.");
} else {
  w(`${cat.duplicates.length} row(s) merged into an existing product.`);
  w();
  w("| Kept | Duplicate row | Matched on | Source | Fields filled | Conflicts |");
  w("|---|---|---|---|---|---:|");
  for (const d of cat.duplicates) {
    w(
      `| \`${d.keptHandle}\` | \`${d.duplicateOf}\` | ${d.matchedOn} | ${d.file}:${d.row} | ` +
        `${d.filled.length ? d.filled.join(", ") : "none"} | ${d.conflicts.length} |`,
    );
  }
  const conflicted = cat.duplicates.filter((d) => d.conflicts.length);
  if (conflicted.length) {
    w();
    w("### Values the sources disagree on");
    w();
    w("The first value stands. Choosing between two stated facts would mean");
    w("inventing one, so these need a human decision.");
    w();
    w("| Product | Field | Kept | Ignored |");
    w("|---|---|---|---|");
    for (const d of conflicted) {
      for (const c of d.conflicts) {
        w(`| \`${d.keptHandle}\` | ${c.field} | ${c.kept} | ${c.ignored} |`);
      }
    }
  }
}
w();

/* ---------------------------- missing fields --------------------------- */

w("## Missing fields");
w();
w("| Gap | Products | Share |");
w("|---|---:|---:|");
for (const [f, n] of flagCounts) {
  if (!f.startsWith("missing_") && f !== "inventory_unknown" && f !== "no_collection_mapping") continue;
  w(`| ${FLAG_LABEL[f] ?? f} | ${n} | ${Math.round((n / P.length) * 100)}% |`);
}
w();

/* --------------------------- requiring review -------------------------- */

w("## Products requiring review");
w();
w(`${review.length} of ${P.length} products need a person to look at them.`);
w();

if (withheld.length) {
  w("### Withheld from the storefront");
  w();
  w("These import into the catalog but do not render.");
  w();
  w("| Product | Reason |");
  w("|---|---|");
  for (const p of withheld) {
    const why = p.titleMatches.length
      ? `Product name states a banned claim: ${[...new Set(p.titleMatches.map((m) => m.term))].join(", ")}`
      : p.flags.includes("zero_price")
        ? "Price is 0.00"
        : "No price";
    w(`| \`${p.handle}\`<br>${p.title.slice(0, 64)} | ${why} |`);
  }
  w();
}

const quarantined = P.filter((p) => p.quarantinedContent.length);
if (quarantined.length) {
  w("### Copy held for compliance review");
  w();
  w(`${quarantined.length} products have at least one paragraph quarantined. The text`);
  w("stays in the catalog record and is never rendered.");
  w();
  w("| Product | Blocks | Terms |");
  w("|---|---:|---|");
  for (const p of quarantined.sort((a, b) => b.quarantinedContent.length - a.quarantinedContent.length).slice(0, 20)) {
    const terms = [...new Set(p.quarantinedContent.flatMap((q) => q.matches.map((m) => m.term.toLowerCase())))];
    w(`| \`${p.handle}\` | ${p.quarantinedContent.length} | ${terms.slice(0, 6).join(", ")} |`);
  }
  if (quarantined.length > 20) {
    w();
    w(`...and ${quarantined.length - 20} more, all recorded in \`catalog.json\`.`);
  }
  w();
}

const noDesc = P.filter((p) => p.flags.includes("missing_description"));
if (noDesc.length) {
  w("### No description");
  w();
  w("```");
  for (const p of noDesc) w(p.handle);
  w("```");
  w();
}

const noSku = P.filter((p) => p.flags.includes("missing_sku"));
if (noSku.length) {
  w("### No SKU");
  w();
  w(`${noSku.length} products. A SKU is the fallback identity used to deduplicate`);
  w("against future imports, so these will only match on handle.");
  w();
  w("```");
  for (const p of noSku) w(p.handle);
  w("```");
  w();
}

if (cat.skipped.length) {
  w("### Rows skipped");
  w();
  w("| Row | Reason |");
  w("|---|---|");
  for (const s of cat.skipped) w(`| ${s.file ? `${s.file}: ` : ""}\`${s.handle}\` | ${s.reason} |`);
  w();
}

/* ----------------------------- provenance ------------------------------ */

w("## Provenance");
w();
w("Every product records the file and row it came from, so any value can be");
w("traced back to its source.");
w();
w("| Source file | Products |");
w("|---|---:|");
for (const [f, n] of count(
  P.flatMap((p) => p.sources.map((s) => ({ f: s.file }))),
  (x) => x.f,
)) {
  w(`| \`${f}\` | ${n} |`);
}
w();
const multi = P.filter((p) => p.sources.length > 1);
w(
  multi.length
    ? `${multi.length} products were assembled from more than one source row.`
    : "No product was assembled from more than one source row.",
);
w();

writeFileSync(join(root, "docs", "CATALOG-REPORT.md"), `${L.join("\n")}\n`, "utf8");

console.log(`catalog report written to docs/CATALOG-REPORT.md`);
console.log(`  ${P.length} unique products, ${variants.length} variants, ${images.length} images`);
console.log(`  ${published.length} published, ${withheld.length} withheld, ${review.length} need review`);
console.log(`  ${cat.duplicates.length} duplicates merged`);
