/**
 * Water ecosystem catalog: Life Ionizers™ and Pitcher of Life®.
 *
 * Model names, plate counts, installation options, warranty terms and pH
 * ranges are real, verified against public listings (lifeionizers.com,
 * pitcheroflife.com, keytolifesupply.com, lifescienceswater.com).
 *
 * PRICES ARE REPRESENTATIVE PLACEHOLDERS (`pricePlaceholder: true`) -
 * these brands' stores were not reachable from the build environment, so
 * figures must be synced from the live EarthTrade catalog before launch.
 * Products with an empty `images` array render as branded typographic
 * tiles until real product photography is synced; no AI-generated product
 * imagery is used, so actual products are never misrepresented.
 */

import type { Product } from "../lib/types.ts";

const IONIZER_SHARED = {
  brand: "life-ionizers" as const,
  category: "water" as const,
  images: [] as Product["images"],
  pricePlaceholder: true,
};

function ionizerFaqs(model: string): { q: string; a: string }[] {
  return [
    {
      q: `Can the ${model} install under the counter?`,
      a: "Yes. Every MXL system self-installs on the countertop near your sink, or under the counter with a faucet attachment (UC configuration).",
    },
    {
      q: "How often do filters need replacing?",
      a: "MXL replacement filters are rated for 6 to 12 months depending on water quality and usage. The Filter Finder matches your model to the correct replacement.",
    },
  ];
}

export const waterProducts: Product[] = [
  {
    ...IONIZER_SHARED,
    handle: "life-ionizer-mxl-5",
    title: "Life Ionizer Core MXL-5",
    cardTitle: "Core MXL-5",
    collections: ["life-ionizers", "water"],
    shortBenefit: "The 5-plate entry point to alkaline, hydrogen-rich water.",
    description: [
      "The Core MXL-5 brings Life Ionizers' plate technology to its most accessible price point. Five titanium plates dipped in platinum deliver alkaline, hydrogen-rich water at the countertop.",
      "A clean, compact design that fits smaller kitchens without giving up the core of the MXL platform.",
    ],
    benefits: [
      "5-plate ionization system",
      "Countertop installation in minutes",
      "Adjustable pH levels for drinking and household use",
      "Entry point to the MXL ecosystem, same replacement filters",
    ],
    specs: [
      ["Plates", "5 titanium, platinum-coated"],
      ["Installation", "Countertop"],
      ["Filtration", "Internal filter, 6 to 12 month life"],
      ["Series", "MXL Core"],
    ],
    faqs: ionizerFaqs("Core MXL-5"),
    variants: [{ id: "et-mxl5", title: "Core MXL-5", price: 2497, available: true }],
    related: ["life-ionizer-mxl-7", "life-ionizer-mxl-9", "life-mxl-replacement-filter"],
    boughtWith: ["life-mxl-replacement-filter"],
    searchTerms: ["MXL-5", "water ionizer", "alkaline water machine", "countertop ionizer"],
  },
  {
    ...IONIZER_SHARED,
    handle: "life-ionizer-mxl-7",
    title: "Life Ionizer MXL-7",
    cardTitle: "MXL-7",
    collections: ["life-ionizers", "water"],
    shortBenefit: "Seven platinum-coated plates and 450 watts of ionizing power.",
    description: [
      "The MXL-7 combines seven titanium platinum-coated plates with 450 watts of power, producing alkaline, hydrogen-rich water with room to grow into stronger pH ranges.",
      "Installs on the countertop or under the counter with a faucet attachment, and carries a lifetime parts warranty with 10 years of labor coverage.",
    ],
    benefits: [
      "7-plate, 450 watt ionization system",
      "Countertop or under-counter installation",
      "Wide adjustable pH range",
      "Lifetime parts warranty, 10 years labor",
    ],
    specs: [
      ["Plates", "7 titanium, platinum-coated"],
      ["Power", "450 W"],
      ["Installation", "Countertop or under counter (UC)"],
      ["Warranty", "Lifetime parts, 10 years labor"],
    ],
    faqs: ionizerFaqs("MXL-7"),
    variants: [
      { id: "et-mxl7", title: "Countertop", price: 3297, available: true },
      { id: "et-mxl7-uc", title: "Under Counter", price: 3497, available: true },
    ],
    badges: ["popular"],
    related: ["life-ionizer-mxl-9", "life-ionizer-mxl-5", "life-mxl-replacement-filter"],
    boughtWith: ["life-mxl-replacement-filter"],
    searchTerms: ["MXL-7", "water ionizer", "alkaline machine"],
  },
  {
    ...IONIZER_SHARED,
    handle: "life-ionizer-mxl-9",
    title: "Life Ionizer Supreme MXL-9",
    cardTitle: "Supreme MXL-9",
    collections: ["life-ionizers", "water", "best-sellers"],
    shortBenefit: "Top-of-the-line benefits at a mid-range price. The favorite.",
    description: [
      "The Supreme MXL-9 is the sweet spot of the MXL range: nine plates dipped eight times in medical-grade platinum, delivering premium performance without stepping up to flagship pricing.",
      "Installs countertop or under counter, backed by a guaranteed lifetime warranty.",
    ],
    benefits: [
      "9 plates dipped 8 times in medical-grade platinum",
      "Countertop or under-counter installation",
      "Strong pH and antioxidant potential range",
      "Guaranteed lifetime warranty",
    ],
    specs: [
      ["Plates", "9 titanium, 8x platinum-dipped"],
      ["Installation", "Countertop or under counter (UC)"],
      ["Warranty", "Guaranteed lifetime"],
      ["Series", "MXL Supreme"],
    ],
    faqs: ionizerFaqs("Supreme MXL-9"),
    variants: [
      { id: "et-mxl9", title: "Countertop", price: 3997, available: true },
      { id: "et-mxl9-uc", title: "Under Counter", price: 4197, available: true },
    ],
    badges: ["best-seller"],
    related: ["life-ionizer-mxl-11", "life-ionizer-mxl-7", "life-mxl-replacement-filter"],
    boughtWith: ["life-mxl-replacement-filter"],
    searchTerms: ["MXL-9", "water ionizer", "best ionizer"],
  },
  {
    ...IONIZER_SHARED,
    handle: "life-ionizer-mxl-11",
    title: "Life Ionizer MXL-11",
    cardTitle: "MXL-11",
    collections: ["life-ionizers", "water"],
    shortBenefit: "Eleven plates of power for households that drink a lot of water.",
    description: [
      "The MXL-11 is a powerful 11-plate water ionizer built for bigger households and heavier daily use, keeping flow and pH stable when demand climbs.",
      "Installs countertop or under counter, with a guaranteed lifetime warranty.",
    ],
    benefits: [
      "11-plate high-output ionization",
      "Holds performance at higher flow rates",
      "Countertop or under-counter installation",
      "Guaranteed lifetime warranty",
    ],
    specs: [
      ["Plates", "11 titanium, platinum-coated"],
      ["Installation", "Countertop or under counter (UC)"],
      ["Warranty", "Guaranteed lifetime"],
    ],
    faqs: ionizerFaqs("MXL-11"),
    variants: [
      { id: "et-mxl11", title: "Countertop", price: 4497, available: true },
      { id: "et-mxl11-uc", title: "Under Counter", price: 4697, available: true },
    ],
    related: ["life-ionizer-mxl-9", "life-ionizer-mxl-15", "life-mxl-replacement-filter"],
    boughtWith: ["life-mxl-replacement-filter"],
    searchTerms: ["MXL-11", "water ionizer", "11 plate"],
  },
  {
    ...IONIZER_SHARED,
    handle: "life-ionizer-mxl-13",
    title: "Life Ionizer MXL-13",
    cardTitle: "MXL-13",
    collections: ["life-ionizers", "water"],
    shortBenefit: "Thirteen plates for near-flagship output and range.",
    description: [
      "One step below the flagship, the MXL-13 delivers thirteen plates of ionizing surface for demanding households that want maximum range without the Apex price.",
      "Installs countertop or under counter, with a guaranteed lifetime warranty.",
    ],
    benefits: [
      "13-plate ionization system",
      "Near-flagship pH and output range",
      "Countertop or under-counter installation",
      "Guaranteed lifetime warranty",
    ],
    specs: [
      ["Plates", "13 titanium, platinum-coated"],
      ["Installation", "Countertop or under counter (UC)"],
      ["Warranty", "Guaranteed lifetime"],
    ],
    faqs: ionizerFaqs("MXL-13"),
    variants: [{ id: "et-mxl13", title: "MXL-13", price: 4797, available: true }],
    related: ["life-ionizer-mxl-15", "life-ionizer-mxl-11", "life-mxl-replacement-filter"],
    boughtWith: ["life-mxl-replacement-filter"],
    searchTerms: ["MXL-13", "water ionizer"],
  },
  {
    ...IONIZER_SHARED,
    handle: "life-ionizer-mxl-15",
    title: "Life Ionizer Apex MXL-15",
    cardTitle: "Apex MXL-15",
    collections: ["life-ionizers", "water"],
    shortBenefit: "The flagship: fifteen plates, maximum power and range.",
    description: [
      "The Apex MXL-15 is the flagship of the Life Ionizers range. Fifteen plates deliver the widest pH range, the strongest hydrogen potential and the highest flow in the MXL line.",
      "For households that want the most capable machine available, installed countertop or under counter, with a guaranteed lifetime warranty.",
    ],
    benefits: [
      "15-plate flagship ionization system",
      "Widest pH and antioxidant potential range in the line",
      "Highest flow rate of the MXL series",
      "Guaranteed lifetime warranty",
    ],
    specs: [
      ["Plates", "15 titanium, platinum-coated"],
      ["Installation", "Countertop or under counter (UC)"],
      ["Warranty", "Guaranteed lifetime"],
      ["Series", "MXL Apex"],
    ],
    faqs: ionizerFaqs("Apex MXL-15"),
    variants: [
      { id: "et-mxl15", title: "Countertop", price: 4997, available: true },
      { id: "et-mxl15-uc", title: "Under Counter", price: 5197, available: true },
    ],
    badges: ["premium"],
    related: ["life-ionizer-mxl-13", "life-ionizer-mxl-9", "life-mxl-replacement-filter"],
    boughtWith: ["life-mxl-replacement-filter"],
    searchTerms: ["MXL-15", "flagship ionizer", "best water ionizer"],
  },
  {
    ...IONIZER_SHARED,
    handle: "life-mxl-replacement-filter",
    title: "Life MXL Replacement Filter",
    cardTitle: "MXL Replacement Filter",
    collections: ["life-ionizers", "water-filtration", "water"],
    shortBenefit: "The right filter for every MXL model, rated 6 to 12 months.",
    description: [
      "Keep your Life Ionizer performing like day one. MXL replacement filters fit all MXL models and are rated for 6 to 12 months of use depending on your water quality.",
      "Not sure which filter your system takes? The Filter Finder matches your model to the correct replacement in a few clicks.",
    ],
    benefits: [
      "Fits all MXL series models",
      "6 to 12 month filter life",
      "Maintains flow and filtration performance",
      "Available on Auto-Ship so you never run out",
    ],
    specs: [
      ["Compatibility", "All Life MXL models"],
      ["Filter life", "6 to 12 months"],
    ],
    variants: [{ id: "et-mxl-filter", title: "Replacement Filter", price: 99, available: true }],
    badges: ["subscription"],
    subscription: true,
    replenish: { intervalDays: 270, note: "Replace every 6 to 12 months depending on water quality." },
    related: ["life-ionizer-mxl-9", "pitcher-of-life-replacement-filter-3pack"],
    searchTerms: ["MXL filter", "ionizer filter", "replacement filter"],
  },

  // Pitcher of Life®
  {
    handle: "pitcher-of-life-2nd-generation",
    title: "Pitcher of Life Alkaline Water Pitcher (2nd Generation)",
    cardTitle: "Alkaline Water Pitcher, 2nd Gen",
    brand: "pitcher-of-life",
    category: "water",
    collections: ["pitcher-of-life", "water", "best-sellers"],
    shortBenefit: "Alkaline water at 8.5 to 9.5 pH, one pour at a time.",
    description: [
      "The second-generation Pitcher of Life turns tap water into alkaline water with a 6-stage filter cartridge that reduces heavy metals, chlorine taste and other contaminants while adding calcium, magnesium and potassium minerals.",
      "A 3.8 liter body with a 2 liter filtering capacity keeps the whole household poured, and drop-in replacement filters make upkeep simple.",
    ],
    benefits: [
      "Raises water to 8.5 to 9.5 pH",
      "6-stage filter reduces heavy metals and chlorine taste",
      "Adds calcium, magnesium and potassium minerals",
      "3.8 L capacity, simple drop-in filter replacement",
    ],
    specs: [
      ["Capacity", "3.8 L (2 L filtering)"],
      ["pH range", "8.5 to 9.5"],
      ["Filter", "6-stage cartridge"],
    ],
    images: [],
    variants: [{ id: "et-pol-2g", title: "2nd Generation Pitcher", price: 47.97, available: true }],
    badges: ["best-seller"],
    pricePlaceholder: true,
    related: ["pitcher-of-life-2nd-generation-3pack-replacement-filter", "pitcher-with-copper-bottle", "borosilicate-pitcher-filter-bundle"],
    boughtWith: ["pitcher-of-life-2nd-generation-3pack-replacement-filter"],
    searchTerms: ["alkaline pitcher", "water pitcher", "pitcher of life"],
  },
  {
    handle: "pitcher-with-copper-bottle",
    title: "Flower of Life Alkaline Water Pitcher with Copper Bottle",
    cardTitle: "Flower of Life Pitcher + Copper Bottle",
    brand: "pitcher-of-life",
    category: "water",
    collections: ["pitcher-of-life", "water", "accessories"],
    shortBenefit: "The alkaline pitcher paired with a Flower of Life copper bottle.",
    description: [
      "The Flower of Life edition pairs the 3.8 liter alkaline pitcher with a copper bottle carrying the Flower of Life symbol, so better water travels with you.",
      "The 6-stage filter cartridge reduces heavy metals, chlorine taste and other contaminants while adding calcium, magnesium and potassium minerals, creating 8.5 to 9.5 pH water.",
    ],
    benefits: [
      "3.8 L alkaline pitcher, 8.5 to 9.5 pH",
      "6-stage filtration with added minerals",
      "Includes copper bottle with Flower of Life symbol",
      "A complete at-home and on-the-go water set",
    ],
    specs: [
      ["Pitcher capacity", "3.8 L (2 L filtering)"],
      ["pH range", "8.5 to 9.5"],
      ["Included", "Pitcher, 6-stage filter, copper bottle"],
    ],
    images: [],
    variants: [{ id: "et-pol-fol-copper", title: "Pitcher + Copper Bottle", price: 79.97, available: true }],
    badges: ["premium"],
    pricePlaceholder: true,
    related: ["pitcher-of-life-2nd-generation", "flower-of-life-copper-bottle"],
    boughtWith: ["pitcher-of-life-replacement-filter-3pack"],
    searchTerms: ["flower of life", "copper bottle", "alkaline pitcher set"],
  },
  {
    handle: "borosilicate-pitcher-filter-bundle",
    title: "Borosilicate Glass Pitcher with Infuser + 3 Filters Bundle",
    cardTitle: "Glass Pitcher + 3 Filters Bundle",
    brand: "pitcher-of-life",
    category: "water",
    collections: ["pitcher-of-life", "water"],
    shortBenefit: "The glass pitcher with infuser, bundled with three filters.",
    description: [
      "A borosilicate glass body with a fruit and botanical infuser, bundled with three 6-stage alkaline filters so the first year of better water is covered from day one.",
    ],
    benefits: [
      "Borosilicate glass body with infuser",
      "Bundled with three 6-stage alkaline filters",
      "Bundle savings versus buying separately",
    ],
    specs: [
      ["Material", "Borosilicate glass"],
      ["Included", "Pitcher, infuser, 3 filters"],
    ],
    images: [],
    variants: [
      { id: "et-pol-glass-bundle", title: "Glass Pitcher + 3 Filters", price: 117.97, compareAt: 142.97, available: true },
    ],
    badges: ["new"],
    pricePlaceholder: true,
    related: ["pitcher-of-life-2nd-generation", "pitcher-of-life-replacement-filter-3pack"],
    searchTerms: ["glass pitcher", "infuser pitcher", "pitcher bundle"],
  },
  {
    handle: "pitcher-of-life-replacement-filter",
    title: "Pitcher of Life Replacement Filter",
    cardTitle: "Replacement Filter",
    brand: "pitcher-of-life",
    category: "water",
    collections: ["pitcher-of-life", "water-filtration", "water"],
    shortBenefit: "The 6-stage drop-in filter for first-generation pitchers.",
    description: [
      "The drop-in 6-stage replacement filter for the original Pitcher of Life. Improves taste and clarity while creating 8.5 to 9.5 pH alkaline water.",
      "Over 3,000,000 of these alkaline filters have been purchased by Pitcher of Life customers.",
    ],
    benefits: [
      "Drops right into the original Pitcher of Life",
      "6-stage filtration, 8.5 to 9.5 pH",
      "Improves taste and clarity",
    ],
    specs: [
      ["Compatibility", "Pitcher of Life (1st generation)"],
      ["Filter life", "About 2 months of typical use"],
    ],
    images: [],
    variants: [{ id: "et-pol-filter-1", title: "Single Filter", price: 24.97, available: true }],
    pricePlaceholder: true,
    subscription: true,
    badges: ["subscription"],
    replenish: { intervalDays: 60, note: "Replace about every 2 months for best taste." },
    related: ["pitcher-of-life-replacement-filter-3pack", "pitcher-of-life-2nd-generation"],
    searchTerms: ["pitcher filter", "replacement filter", "alkaline filter"],
  },
  {
    handle: "pitcher-of-life-replacement-filter-3pack",
    title: "Pitcher of Life Replacement Filters – 3 Pack",
    cardTitle: "Replacement Filters, 3 Pack",
    brand: "pitcher-of-life",
    category: "water",
    collections: ["pitcher-of-life", "water-filtration", "water", "best-sellers"],
    shortBenefit: "Three filters, about six months of better water, better price.",
    description: [
      "The economical way to keep the water flowing: three 6-stage filters, working out to about $19.99 per filter, covering roughly six months of typical use.",
    ],
    benefits: [
      "Three 6-stage alkaline filters",
      "About six months of typical use",
      "Better per-filter price than singles",
      "Available on Auto-Ship so you never run out",
    ],
    specs: [
      ["Compatibility", "Pitcher of Life (1st generation)"],
      ["Pack", "3 filters"],
    ],
    images: [],
    variants: [{ id: "et-pol-filter-3", title: "3 Pack", price: 59.97, available: true }],
    badges: ["best-seller", "subscription"],
    pricePlaceholder: true,
    subscription: true,
    replenish: { intervalDays: 180, note: "A 3-pack covers about six months." },
    related: ["pitcher-of-life-replacement-filter", "pitcher-of-life-2nd-generation-3pack-replacement-filter"],
    searchTerms: ["filter 3 pack", "pitcher filters", "auto ship filters"],
  },
  {
    handle: "pitcher-of-life-2nd-generation-3pack-replacement-filter",
    title: "Pitcher of Life 2nd Generation Replacement Filters – 3 Pack",
    cardTitle: "2nd Gen Filters, 3 Pack",
    brand: "pitcher-of-life",
    category: "water",
    collections: ["pitcher-of-life", "water-filtration", "water"],
    shortBenefit: "The 3-pack for second-generation pitchers.",
    description: [
      "Three 6-stage replacement filters sized for the second-generation Pitcher of Life, covering roughly six months of typical use.",
    ],
    benefits: [
      "Fits the 2nd generation Pitcher of Life",
      "Three 6-stage alkaline filters",
      "Available on Auto-Ship so you never run out",
    ],
    specs: [
      ["Compatibility", "Pitcher of Life (2nd generation)"],
      ["Pack", "3 filters"],
    ],
    images: [],
    variants: [{ id: "et-pol2-filter-3", title: "3 Pack", price: 59.97, available: true }],
    badges: ["subscription"],
    pricePlaceholder: true,
    subscription: true,
    replenish: { intervalDays: 180, note: "A 3-pack covers about six months." },
    related: ["pitcher-of-life-2nd-generation", "pitcher-of-life-replacement-filter-3pack"],
    searchTerms: ["2nd gen filter", "pitcher filters"],
  },
  {
    handle: "flower-of-life-copper-bottle",
    title: "Flower of Life Copper Bottle",
    cardTitle: "Copper Bottle",
    brand: "pitcher-of-life",
    category: "wellness",
    collections: ["pitcher-of-life", "accessories", "wellness"],
    shortBenefit: "A handcrafted copper bottle carrying the Flower of Life symbol.",
    description: [
      "A classic copper water bottle finished with the Flower of Life symbol. Copper vessels have carried water in daily rituals for centuries; this one brings that tradition to the modern table.",
    ],
    benefits: [
      "Solid copper construction",
      "Flower of Life symbol",
      "Pairs with the Pitcher of Life at home",
    ],
    specs: [["Material", "Copper"]],
    images: [],
    variants: [{ id: "et-copper-bottle", title: "Copper Bottle", price: 34.97, available: true }],
    pricePlaceholder: true,
    related: ["pitcher-with-copper-bottle", "pitcher-of-life-2nd-generation"],
    searchTerms: ["copper bottle", "water bottle", "flower of life"],
  },
];
